mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  port: 8080
spring:
  application:
    name: bbs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: NewPassword
    url: jdbc:mysql://localhost:3306/bbs2020
    username: root