mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: top.xiongmingcai.bbs.mybatis.entity

server:
  port: 8080
spring:
  application:
    name: bbs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: NewPassword
    url: jdbc:mysql://localhost:3306/bbs2020?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false&amp;serverTimezone=GMT
    username: root